version: "3.1"
services:
    www:
        image: eu.gcr.io/jubba-264720/apache:7.3
        ports: 
            - "80:80"
        volumes:
            - ./:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: eu.gcr.io/jubba-264720/mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: duha
            MYSQL_PASSWORD: 123qwe
            MYSQL_ROOT_PASSWORD: 123qwe 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: eu.gcr.io/jubba-264720/phpmyadmin:5
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: duha
            MYSQL_PASSWORD: 123qwe
            MYSQL_ROOT_PASSWORD: 123qwe 
volumes:
    persistent:
